# Generated by Django 5.2.4 on 2025-07-22 11:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestener_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
        ),
    ]
