# Generated by Django 5.2.4 on 2025-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.AddField(
            model_name='application',
            name='settlement',
            field=models.CharField(default='', max_length=64, verbose_name='Населённый пункт'),
            preserve_default=False,
        ),
    ]
