# Generated by Django 5.2.4 on 2025-07-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_city_application_settlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
