# Generated by Django 5.2.4 on 2025-07-24 05:49

import django.db.models.deletion
import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_env_variable_name', models.CharField(max_length=128, unique=True, validators=[shared.models.validators.env_variable_name_validator], verbose_name='Название ENV-переменной с токеном этого бота')),
            ],
        ),
        migrations.CreateModel(
            name='TelegrammBotSendingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(verbose_name='ID чата для отправки уведомления')),
                ('bot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.telegrambot', verbose_name='Телеграм бот для отправки уведомления')),
            ],
            options={
                'verbose_name': 'Настройки Telegram уведомлений',
                'verbose_name_plural': 'Настройки Telegram уведомлений',
            },
        ),
    ]
