# Generated by Django 5.2.4 on 2025-07-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_telegrambot_telegrammbotsendingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammbotsendingsettings',
            name='channel_id',
            field=models.IntegerField(null=True, verbose_name='ID чата для отправки уведомления'),
        ),
    ]
