# Generated by Django 5.2.4 on 2025-07-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_telegrammbotsendingsettings_channel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Телеграм бот', 'verbose_name_plural': 'Телеграм боты'},
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='assignment',
            field=models.CharField(default='', help_text='Ни на что не влияет', max_length=512, verbose_name='Предназначение'),
            preserve_default=False,
        ),
    ]
