# Generated by Django 5.2.4 on 2025-07-24 06:10

import django.db.models.deletion
import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_telegrambot_options_telegrambot_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='assignment',
            field=models.CharField(help_text='Ни на что не влияет', max_length=512, verbose_name='Предназначен для'),
        ),
        migrations.AlterField(
            model_name='telegrammbotsendingsettings',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.telegrambot', verbose_name='Телеграм бот для отправки уведомления'),
        ),
        migrations.AlterField(
            model_name='telegrammbotsendingsettings',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True, validators=[shared.models.validators.string_is_correct_numeric_validator], verbose_name='ID чата для отправки уведомления'),
        ),
    ]
