# Generated by Django 5.2.4 on 2025-07-24 06:11

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_telegrambot_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammbotsendingsettings',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=64, validators=[shared.models.validators.string_is_correct_numeric_validator], verbose_name='ID чата для отправки уведомления'),
            preserve_default=False,
        ),
    ]
