# Generated by Django 5.2.4 on 2025-07-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_telegrammbotsendingsettings_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrammbotsendingsettings',
            old_name='bot',
            new_name='bot_for_notifications',
        ),
        migrations.RenameField(
            model_name='telegrammbotsendingsettings',
            old_name='channel_id',
            new_name='notifications_channel_id',
        ),
    ]
