# Generated by Django 5.2.4 on 2025-07-28 06:49

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения заявки'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='token_env_variable_name',
            field=models.CharField(max_length=128, unique=True, validators=[shared.models.validators.env_variable_name_validator], verbose_name='ENV-переменная с токеном'),
        ),
        migrations.AlterField(
            model_name='telegrammbotsendingsettings',
            name='notifications_channel_id',
            field=models.CharField(blank=True, help_text='Либо число, либо отрицательное число для группы, согласно документации telegram.', max_length=64, validators=[shared.models.validators.string_is_correct_numeric_validator], verbose_name='ID чата для отправки уведомления'),
        ),
    ]
