# Generated by Django 5.2.4 on 2025-07-22 04:49

import pathlib
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('question', models.CharField(max_length=512, unique=True, verbose_name='Вопрос')),
                ('answer', tinymce.models.HTMLField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ пункт',
                'verbose_name_plural': 'FAQ пункты',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Выплаты',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.CreateModel(
            name='RecruitersContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контакты вербовщиков',
                'verbose_name_plural': 'Контакты вербовщиков',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_favicon', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/LastTrainingProject/media/icons'), verbose_name='Favicon сайта')),
                ('site_video', models.FileField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/LastTrainingProject/media/videos'), verbose_name='Видео')),
                ('robots_txt_content', models.TextField(blank=True, verbose_name='Контент Robots.txt')),
                ('html_head_addition', models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в html разметку', verbose_name='Добавить в <head>')),
                ('html_body_addition', models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в html разметку', verbose_name='Добавить в <body>')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
