# Generated by Django 5.2.4 on 2025-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitersBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контакты вербовщиков',
                'verbose_name_plural': 'Контакты вербовщиков',
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='additional_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Дополнительная выплата'),
        ),
        migrations.AddField(
            model_name='payments',
            name='additional_payment_title',
            field=models.CharField(blank=True, max_length=12, verbose_name='Описание дополнительной выплаты'),
        ),
        migrations.AddField(
            model_name='payments',
            name='city_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Единовременная выплата от администрации города'),
        ),
        migrations.AddField(
            model_name='payments',
            name='city_payment_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание выплаты от А. города'),
        ),
        migrations.AddField(
            model_name='payments',
            name='month_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Месячное довольствие'),
        ),
        migrations.AddField(
            model_name='payments',
            name='offensive_ministry_other_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Иные выплаты от М.О'),
        ),
        migrations.AddField(
            model_name='payments',
            name='offensive_ministry_other_payment_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание иных выплат от М.О'),
        ),
        migrations.AddField(
            model_name='payments',
            name='offensive_ministry_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Единовременная выплата от М.О'),
        ),
        migrations.AddField(
            model_name='payments',
            name='offensive_ministry_payment_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание выплаты от М.О'),
        ),
        migrations.AddField(
            model_name='payments',
            name='regional_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Единовременная выплата от администрации области'),
        ),
        migrations.AddField(
            model_name='payments',
            name='regional_payment_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание выплаты от А. области'),
        ),
        migrations.AddField(
            model_name='payments',
            name='total_first_montch_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Суммарная плата за первый месяц'),
        ),
        migrations.AddField(
            model_name='payments',
            name='total_first_year_payment',
            field=models.CharField(blank=True, max_length=12, verbose_name='Суммарная плата за первый год'),
        ),
        migrations.AddField(
            model_name='recruiterscontacts',
            name='dzen_contact_link',
            field=models.URLField(blank=True, verbose_name='Дзен'),
        ),
        migrations.AddField(
            model_name='recruiterscontacts',
            name='ok_contact_link',
            field=models.URLField(blank=True, verbose_name='Одноклассники'),
        ),
        migrations.AddField(
            model_name='recruiterscontacts',
            name='tg_contact_link',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='recruiterscontacts',
            name='vk_contact_link',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
    ]
