# Generated by Django 5.2.4 on 2025-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_recruitersbranches_payments_additional_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitersbranches',
            options={'verbose_name': 'Филлиалы вербовщиков', 'verbose_name_plural': 'Филлиалы вербовщиков'},
        ),
        migrations.RenameField(
            model_name='recruiterscontacts',
            old_name='ok_contact_link',
            new_name='classmates_contact_link',
        ),
        migrations.AlterField(
            model_name='recruiterscontacts',
            name='vk_contact_link',
            field=models.URLField(blank=True, verbose_name='Вконтакте'),
        ),
    ]
