# Generated by Django 5.2.4 on 2025-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_recruitersbranches_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitersbranches',
            name='addres',
            field=models.CharField(default='hell', max_length=512, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitersbranches',
            name='number_phone',
            field=models.CharField(default='6 666 666 66 66', max_length=256, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
