# Generated by Django 5.2.4 on 2025-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_recruitersbranches_addres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitersbranches',
            name='coordinates',
            field=models.CharField(blank=True, max_length=128, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='recruitersbranches',
            name='addres',
            field=models.CharField(max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='recruitersbranches',
            name='number_phone',
            field=models.CharField(max_length=128, verbose_name='Телефон'),
        ),
    ]
