# Generated by Django 5.2.4 on 2025-07-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_recruitersbranches_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitersbranches',
            options={'verbose_name': 'Филлиал вербовщиков', 'verbose_name_plural': 'Филлиалы вербовщиков'},
        ),
        migrations.AddField(
            model_name='recruitersbranches',
            name='_link_to_contacts_for_admin_model_inline_drawning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.recruiterscontacts'),
            preserve_default=False,
        ),
    ]
