# Generated by Django 5.2.4 on 2025-07-22 10:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_recruitersbranches_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Без .html', unique=True, verbose_name='Название файла')),
                ('name', models.CharField(verbose_name='Название')),
                ('title', models.CharField(help_text='Название вкладки')),
                ('ceo_content', tinymce.models.HTMLField(verbose_name='CEO контент')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='faqpoint',
            name='question',
            field=models.CharField(unique=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='additional_payment',
            field=models.CharField(blank=True, verbose_name='Сумма дополнительной выплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='additional_payment_title',
            field=models.CharField(blank=True, verbose_name='Описание дополнительной выплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='city_payment',
            field=models.CharField(blank=True, verbose_name='Сумма единовременной выплаты от А. города'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='city_payment_title',
            field=models.CharField(blank=True, verbose_name='Описание выплаты от администрации города'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='month_payment',
            field=models.CharField(blank=True, verbose_name='Месячное довольствие'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='offensive_ministry_other_payment',
            field=models.CharField(blank=True, verbose_name='Сумма иной выплаты от Мин.О'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='offensive_ministry_other_payment_title',
            field=models.CharField(blank=True, verbose_name='Описание иной выплаты от Мин.О'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='offensive_ministry_payment',
            field=models.CharField(blank=True, verbose_name='Сумма единовременной выплаты от Мин.О'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='offensive_ministry_payment_title',
            field=models.CharField(blank=True, verbose_name='Описание выплаты от Мин.О'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='regional_payment',
            field=models.CharField(blank=True, verbose_name='Сумма единовременной выплаты от А. области'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='regional_payment_title',
            field=models.CharField(blank=True, verbose_name='Описание выплаты от администрации области'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='total_first_montch_payment',
            field=models.CharField(blank=True, verbose_name='Суммарная плата за первый месяц'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='total_first_year_payment',
            field=models.CharField(blank=True, verbose_name='Суммарная плата за первый год'),
        ),
        migrations.AlterField(
            model_name='recruitersbranches',
            name='addres',
            field=models.CharField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='recruitersbranches',
            name='coordinates',
            field=models.CharField(blank=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='recruitersbranches',
            name='number_phone',
            field=models.CharField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='html_body_addition',
            field=models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в html разметке', verbose_name='Добавить в <body>'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='html_head_addition',
            field=models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в html разметке', verbose_name='Добавить в <head>'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots_txt_content',
            field=models.TextField(blank=True, verbose_name='Содержимое Robots.txt'),
        ),
    ]
