# Generated by Django 5.2.4 on 2025-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_pagecontent_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(help_text='Название вкладки в браузере'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='html_body_addition',
            field=models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в каждой html разметке на сайте', verbose_name='Добавить в <body>'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='html_head_addition',
            field=models.TextField(blank=True, help_text='Этот текст будет добавлен в указанный тег в каждой html разметке на сайте', verbose_name='Добавить в <head>'),
        ),
    ]
