# Generated by Django 5.2.4 on 2025-07-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_pagecontent_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageContent',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='total_first_montch_payment',
            new_name='total_first_month_payment',
        ),
    ]
