# Generated by Django 5.2.4 on 2025-07-28 06:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_pagecontent_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ceo_content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='CEO контент'),
        ),
    ]
