# Generated by Django 5.2.4 on 2025-07-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_page_ceo_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruitersBranches',
            new_name='RecruitersBranche',
        ),
    ]
